name: epigenome-ssm
channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake
  - numpy
  - matplotlib
  - seaborn
  - ucsc-bigwigaverageoverbed
  - ucsc-bedgraphpack
  - ucsc-bedgraphtobigwig